config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/create_fast",  to: "users#create_fast"
  get "/main", to: "users#main"
  get "/check_user", to: "users#check_user"
  get "/create_new_post", to: "users#create_post"
  #get "/create_new_from_user", to: "users#create_new_from_user"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

	has_many :posts

	validates :email, presence: true, uniqueness: true
	#validates :pass, presence: true, length: {minimum: 1}
	#validates :name, length: {minimum: 2}

	#errors go to u.errors(activeerror, array)
	#errors << ["adasdasdad"]
	
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]


  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if is_same_user(@post.user_id)
    else 
      redirect_to posts_url, notice: "You are not allow to edit this"
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    if is_same_user(post_params[:user_id])
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to posts_url, notice: "You are not allow to create this"
      return
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if (is_same_user(post_params[:user_id]))
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to posts_url, notice: "You are not allow to update this"
      return
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :msg)
    end

  def is_same_user(check_id)
    #puts "==============user_id #{check_id.class}" #string
    #puts "==============session #{(session[:user_id]).class}" #int
      if (session[:user_id].to_s == check_id.to_s) 
        return true
      else 
        return false
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy] #check_user
  before_action :check_login, only: %i[index new create]
  before_action :is_same_user, only: %i[show edit update delete]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    if (check_login)
    else 
      return false
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else 
        #
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." } #if requested format = html
        format.json { render :show, status: :ok, location: @user } #if requested format = json
      else
        format.html { render :edit, status: :unprocessable_entity } #unprocess of html(error 422)
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @temp = nil
    @temp = @user
    @user.destroy
    #respond_to do |format|
     # format.html { redirect_to users_url, notice: "User was successfully destroyed." }
     # format.json { head :no_content }
    #end
  end

  def create_fast
    @re_name = params[:name]
    @re_email = params[:email]
    User.create(name:@re_name, email:@re_email)
  end

  def main
    @ok = params[:ok]
    #puts "------param ok is #{@ok}"
    session[:user_id] = nil
  end

  def check_user
    @logging_user = User.find_by(email: params[:email])
    if (@logging_user == nil || @logging_user.authenticate(params[:pass]) == false) #authenticate return false
      redirect_to "/main?ok=error", notice:"Email or Password is not correct!"
      #after redirect, the program still execute the next lines till all func done then redirect
      if (@logging_user) 
        session[:user_id] = nil
      end
    else 
      redirect_to "/users/#{User.find_by(email: params[:email]).id}", notice: "Welcome Back!! #{@logging_user.email}"
      
      #after login => create cookie
      session[:user_id] = @logging_user.id
    end

    #auto render here if there is no redirect or render
  end

  def create_post
    @user = User.find_by(id: params[:create_id])
    if (is_same_user)
      @post = Post.create(user_id: params[:create_id])
      puts @post.user_id
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def check_login
      #direct :login do
      #  "http://localhost:3000/main"
      #end
      if (session[:user_id]) 
        return true
      else 
        redirect_to "http://localhost:3000/main", notice: "Please Login!"
        #return false
      end
    end

    def is_same_user
      if (@user == nil || session[:user_id] != @user.id) 
        if (@user == nil) 
          redirect_to "http://localhost:3000/main", notice: "You are not logged in"
        else
          redirect_to "http://localhost:3000/main", notice: "You are not permitted to this content"
        end
      else
        return true
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      #dont for get to put param in this!!!!!!!!!!!!!!
      params.require(:user).permit(:email, :name, :birthday, :address, :postal_code, :pass, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Class4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :msg %>
    <%= form.text_field :msg %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<%= link_to 'Back to User', user_path(@post.user_id) %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Msg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.msg %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Msg:</strong>
  <%= @post.msg %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<%= link_to 'Back to User', "http://localhost:3000/users/#{@post.user_id}" %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <!-- address-->
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <!-- postal_code-->
  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <!-- pass-->
  <div class="field">
    <%= form.label :pass %>
    <%= form.text_field :pass %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <!--<div class="field_with_errors">-->
<% end %>

app/views/users/_form_new_from_user.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :msg %>
    <%= form.text_field :msg %>
    <%= form.hidden_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/check_user.html.erb
<h1>Check User!!! </h1>

<%=@temp%>

app/views/users/create_fast.html.erb
<h1>Welcome to Create_fast!!! </h1>

<br><%="recreated new user ==> name=#{@re_name}, email=#{@re_email}"%>

<br><%= link_to "back to index", "/users"%>

app/views/users/create_post.html.erb
<h1>New Post</h1>

<%= render 'form_new_from_user', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/users/destroy.html.erb
<h1>Delete!</h1>

<br>
<%if @temp!=nil%>
  <%="deleted! : name = #{@temp.name} , email = #{@temp.email}"%>
<%else%>
  <%="Nothing to be done"%>
<%end%>


<br><%= link_to "recreate user here!!!", "/create_fast?name=#{@temp.name}&&email=#{@temp.email}"%>
<br><%= link_to "back to index", "/users"%>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.birthday %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to "Destroy", user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New User', new_user_path %>

app/views/users/main.html.erb
<h1>Login </h1>
<p id="notice"><%= notice %></p>
<%if @ok != "error"%>
  <form action="/check_user" target="_self" method="get">
    <label for="email">Email</label><br>
    <input type="text" id="email" name="email" value=""><br>
    <label for="pass">Password:</label><br>
    <input type="password" id="pass" name="pass" value=""><br><br>
    <input type="submit" value="Submit">
  </form>
<%else%>
  <%= link_to 'Back', "/main" %>
<%end%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Postal Code:</strong>
  <%= @user.postal_code %>
</p>

<p>
  <strong>Pass:</strong>
  <%= @user.pass %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.posts.each do |post| %>
      <tr>
        <td><%= post.msg %></td>
        <td><%= post.created_at%></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to "Destroy", post, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Post', "http://localhost:3000/create_new_post?create_id=#{@user.id}"%>